dist: trusty
sudo: false
language: node_js
node_js: 8.6.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
